baseURL = ""
languageCode = "en-us"
themesDir = "themes"
publishDir = "docs"
title = "JoyyyJen"
theme = "arabica"
sectionPagesMenu = "mainmenu"
googleAnalytics = "UA-113303558-1"
disqusShortname = "ajoy-me"

[blackfriday]
    smartypants = false
    extensions = ["tables", "hardLineBreak", "fencedCode"]
    smartDashes = false

[params]
    description = "四處瞧瞧，寫寫看看，就醉了"
    dateFormatToUse = "2006-01-02"
    facebook = "野人生活也是很耗功夫的"
    github = "joyyyjen"
    hasCJKLanguage = true
    summarylength = 100

